### ISSUE TITLE
LocusFocus: Internal Server Error

### ISSUE THREAD

**Issue by jielab** [naim-panjwani/LocusFocus#6]
Hi, there:

I was test running LocusFocus, but got the following error. Is this still up running well?

![image](https://user-images.githubusercontent.com/26947455/131238812-e1701efa-d6b1-4cbc-bd31-028f810de3ac.png)

BTW, I must select one region <2MB for analysis, and there is no way to run genome-wide, correct?

Best regards,
Jie

**Comment by naim-panjwani** [comment]
Hello Jie, 

Thank you for the message. 
The app is running well, and I would require the exact steps to replicate this error. 
And yes, you are correct that with the current implementation, only regions <2Mbp are allowed. 

Naim
